### ISSUE TITLE
'BaseValidate' does not exist in the current context

### ISSUE THREAD

**Issue by irtazaali** [TheSMSWorks/smsw-csharp-sdk#1]
On compiling the project I get this issue

Error	CS0103	The name 'BaseValidate' does not exist in the current context	IO.Swagger	smsw-csharp-sdk\src\IO.Swagger\Model\ExtendedErrorModel.cs	169

NuGet Package Info
"JsonSubTypes" version="1.2.0" targetFramework="net45" developmentDependency="true"
"Newtonsoft.Json" version="10.0.3" targetFramework="net45" developmentDependency="true"
"RestSharp" version="105.1.0" targetFramework="net45" developmentDependency="true"

**Comment by irtazaali** [comment]
Error: "The name 'BaseValidate' does not exist in the current context"

Fixed by commenting out the method:
//IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        //{
        //    foreach(var x in BaseValidate(validationContext)) yield return x;
        //    yield break;
        //}

**Comment by TheSMSWorks** [comment]
Thanks @irtazaali. It's related to this issue with the OpenAPI generator tools. Others have worked around the issue in the same manner. We'll update that to match.

https://github.com/OpenAPITools/openapi-generator/issues/5416
